//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class KU_LeaveBalance
    {
        public int EmployeeID { get; set; }
        public int TotalLeaveDays { get; set; }
        public int UsedLeaveDays { get; set; }
        public Nullable<int> RemainingLeaveDays { get; set; }
    }
}
