//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user96_dbEntities1 : DbContext
    {
        public user96_dbEntities1()
            : base("name=user96_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KU_Contacts> KU_Contacts { get; set; }
        public virtual DbSet<KU_Education> KU_Education { get; set; }
        public virtual DbSet<KU_EmployeeChildren> KU_EmployeeChildren { get; set; }
        public virtual DbSet<KU_EmployeeProfessionalData> KU_EmployeeProfessionalData { get; set; }
        public virtual DbSet<KU_Employees> KU_Employees { get; set; }
        public virtual DbSet<KU_Roles> KU_Roles { get; set; }
        public virtual DbSet<KU_SalaryHistory> KU_SalaryHistory { get; set; }
        public virtual DbSet<KU_Users> KU_Users { get; set; }
        public virtual DbSet<KU_EmployeeOfTheMonth> KU_EmployeeOfTheMonth { get; set; }
        public virtual DbSet<KU_Tasks> KU_Tasks { get; set; }
        public virtual DbSet<KU_LeaveBalance> KU_LeaveBalance { get; set; }
        public virtual DbSet<KU_LeaveRequests> KU_LeaveRequests { get; set; }
        public virtual DbSet<KU_HRRequests> KU_HRRequests { get; set; }
    }
}
